apiVersion: v1
kind: Service
metadata:
  name: pakrunner
  namespace: default
spec:
  type: NodePort  # Explicitly set to NodePort
  selector:
    app: pakrunner  # Must match labels in your Deployment
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8080  # Container port (matches your Spring Boot app)
      nodePort: 32333  # Manually set NodePort (must be 30000-32767 on most clusters)

